name: Build AlliedModders extension

on:
  workflow_call:
    inputs:
      sdks:
        description: "Space delimited list of SDKs to build against (e.g., css dods tf2)"
        required: true
        type: string
      artifact-path:
        description: "Artifact path to download from previous jobs"
        default: ""
        type: string
      submodules:
        description: "Whether to checkout submodules (true, false, or recursive)"
        default: "recursive"
        type: string
      mm-branch:
        description: "The MetaMod Repository branch to compile the extension against"
        default: "1.12-dev"
        type: string

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - windows-2022
        sm-branch:
          - master
          - 1.12-dev
        include:
          - os: ubuntu-24.04
            cc: clang-14
            cxx: clang++-14
          - os: windows-2022
            cc: msvc
            cxx: msvc

    name: ${{ matrix.os }} (SM ${{ matrix.sm-branch }})
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: ${{ inputs.submodules }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Compiler and 32-bit Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y \
            clang-14 \
            clang++-14 \
            gcc-multilib \
            g++-multilib \
            lib32stdc++6 \
            linux-libc-dev:i386

      - name: Download artifact
        uses: actions/download-artifact@v4
        if: inputs.artifact-path != ''
        with:
          path: ${{ inputs.artifact-path }}

      - name: Checkout SourceMod
        shell: bash
        run: |
          mkdir sourcemod
          cd sourcemod
          git init -b master
          git remote add origin https://github.com/alliedmodders/sourcemod.git
          if [ "${{ matrix.sm-branch }}" = "master" ]; then
            git fetch --depth 100 origin master
            git checkout 42ce2ce
          else
            git fetch --depth 1 origin ${{ matrix.sm-branch }}
            git checkout FETCH_HEAD
          fi

      - name: Checkout MetaMod
        shell: bash
        run: |
          git clone --depth 1 --branch ${{ inputs.mm-branch }} https://github.com/alliedmodders/metamod-source.git mmsource

      - name: Checkout and Install AMBuild
        shell: bash
        run: |
          git clone --depth 1 https://github.com/alliedmodders/ambuild.git ambuild
          python3 -m pip install ./ambuild

      - name: Checkout HL2SDK Manifests
        shell: bash
        run: |
          git clone --depth 1 https://github.com/alliedmodders/hl2sdk-manifests.git hl2sdk-manifests

      - name: Checkout HL2SDKs
        shell: bash
        run: |
          for sdk in ${{ inputs.sdks }}; do
            echo "Cloning hl2sdk-$sdk..."
            git clone --depth 1 --branch $sdk https://github.com/alliedmodders/hl2sdk.git hl2sdk-$sdk
          done

      - name: Build Extension
        shell: bash
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        run: |
          mkdir build
          cd build
          python3 ../sm-ext-common/configure.py --enable-optimize --enable-auto-versioning --ext-root "../"
          ambuild

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-sm-${{ matrix.sm-branch }}
          path: build/package
          if-no-files-found: error
          retention-days: 14

  release:
    name: Github release
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./gh-artifacts

      - name: Package artifacts
        shell: bash
        working-directory: gh-artifacts
        run: |
          for platform in *; do
            if [ -d "./$platform/" ]; then
              cd "./$platform/"
              tar -czf "../${{ github.event.repository.name }}-${platform,,}.tar.gz" -T <(ls -1)
              cd -
            fi
          done

      - name: Release packages
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: './gh-artifacts/*.tar.gz'
          tag: ${{ github.ref }}
          file_glob: true
